require("core.keymaps")
require("core.filetypes")
require("core.options")
require("core.saveactions")
require("core.terminal")
require("core.neovide")
require("core.commandalias")
require("core.github_workflow_picker")
